export const GET_DOGS="GET_DOGS";
export const GET_DOG_BY_ID="GET_DOG_BY_ID";
export const CLEAN_DETAIL="CLEAN_DETAIL";
export const GET_TEMPERAMENTS="GET_TEMPERAMENTS";
export const GET_DOGS_BY_NAME="GET_DOGS_BY_NAME";
export const FILTER_ORIGIN="FILTER_ORIGIN";
export const FILTER_TEMPERAMENT="FILTER_TEMPERAMENT";
export const ORDER_DOGS="ORDER_DOGS";

